### PR TITLE
Add a query file with SQL queries used to find malicious packages.

### PR DESCRIPTION
**Pull request by calebbrown**
These are queries that I've plugged into the BigQuery SQL Explorer to find malicious packages.

I created a table function to make it easier to change phase:

```sql
CREATE TABLE FUNCTION `ossf-malware-analysis.packages`.analysis_for_phase(phase STRING) AS (
    SELECT Package, CreatedTimestamp, phase AS Phase,
    CASE phase
      WHEN "install" THEN Analysis.install
      WHEN "import" THEN Analysis.import
    END AS Result
    FROM `ossf-malware-analysis.packages.analysis`
);
```

Signed-off-by: Caleb Brown <calebbrown@google.com>

### CODE REVIEW

**Comment by maxfisher-g** [comment]
Nice!! Should we add some brief info on how to run a query (for this project) under the top heading? The content that is there looks good though

**Comment by adaluong** [comment]
This is great - thanks Caleb! Adding some brief info for running the query would be super helpful. Also, is there documentation on what A vs AAAA for the QueryType is?

**Review by adaluong — APPROVED** [review]

**Comment by calebbrown** [comment]
> what A vs AAAA for the QueryType is?

Take a look at this [List of DNS Record types](https://en.wikipedia.org/wiki/List_of_DNS_record_types)

**Comment by calebbrown** [comment]
> Nice!! Should we add some brief info on how to run a query (for this project) under the top heading? The content that is there looks good though

Done!

**Review by maxfisher-g — APPROVED** [review]

**Pull request merged**
