### PR TITLE
Refactor docker/* targets in Makefile

### LINKED ISSUE #647: Bring Makefile naming in line with criticality score
The criticality_score project uses PHONY targets with paths:

e.g:
build/images
build/images/analysis
build/images/scheduler
build/images/python_sandbox

This is useful because the hierarchical naming makes it easy to figure out what the more general case is (i.e. build all would be make build).

### PR DESCRIPTION
**Pull request by gliptak**
Fixes #647

### CODE REVIEW

**Comment by gliptak** [comment]
@maxfisher-g please review

**Comment by maxfisher-g** [comment]
Hi @gliptak, thanks for your continued work on this issue!

Looking at the linked issue and example Makefile, I think the 'top level' recipes should be verbs like `build`, `sync`, `push` etc. We probably don't need the `docker` prefix for everything.

Additionally, can we make it so that

- `make build` will build the prod images and sandboxes
- `make push` will push the prod images and sandboxes (after building, as currently)
- `make sync` will sync all sandboxes (after building, as currently)

Thanks very much!

**Comment by gliptak** [comment]
updated. please let me know

**Comment by maxfisher-g** [comment]
@gliptak nice, thank you!

One more thing, if you look at the original comment in #647, the format of the recipes is like `build/image/XXX`. This means that `build/image` will build all the non-sandbox images and `build/sandbox` will build all the sandboxes, etc.

Currently, the recipes in our Makefile look like e.g. `build/XXX_image`, `sync/XXX_sandbox`. Are you able to change the format from this to e.g. `build/image/XXX`, `sync/sandbox/XXX`?

This would be much appreciated :)

**Comment by gliptak** [comment]
@maxfisher-g thank you. updated

**Comment by maxfisher-g** [comment]
Thanks for the update @gliptak! 

Could you please add an entry for `sync` to the output of `make help`, and then I think we can merge this PR :) 

The group targets e.g. `make build/image` , `make sync/sandbox` don't work currently, but this can be fixed in another PR.

**Comment by gliptak** [comment]
@maxfisher-g updated sync

**Review by maxfisher-g — APPROVED** [review]

**Comment by maxfisher-g** [comment]
@gliptak thank you! I'll merge ;)

**Pull request merged**
